# Generated by Django 3.0.5 on 2020-04-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
    ]
