# Generated by Django 3.0.5 on 2020-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/profile_pics/default_img.png', null=True, upload_to=''),
        ),
    ]
